version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket lambda-buc121 --output-template-file outputTemplate.yaml

artifacts:
  type: zip
  files:
    - template.yaml
    - outputTemplate.yaml
