AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: MyLambdaFunction
      Runtime: python3.7
      CodeUri: ./countries
      Handler: index.lambda_handler
      Timeout: 60
      MemorySize: 128
      Events:
        HttpApi:
          Type: HttpApi
          Properties:
            Path: /get-country-data
            Method: get
            
#   version:
#     Type: AWS::Lambda::Version
#     Properties:
#       FunctionName: !Ref MyLambdaFunction
#       Description: v1
#   alias:
#     Type: AWS::Lambda::Alias
#     Properties:
#       FunctionName: !Ref MyLambdaFunction
#       FunctionVersion: !GetAtt version.Version
#       Name: BLUE
       

     
